version: "3.3"

services:
  postgresql:
    image: "arm64v8/postgres:15-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
